### ISSUE TITLE
Leaking memory?

### ISSUE THREAD

**Issue by lgrapenthin** [stuartsierra/dependency#4]
I wonder whether this is intended and if so I'd be interested in knowing why

```clojure
(-> (dep/graph)
    (dep/depend :a :b)
    (dep/remove-edge :a :b))

;-> {:dependencies {:a #{}}, :dependents {:b #{}}}

(-> (dep/graph)
    (dep/depend :a :b)
    (dep/remove-all :a))

;-> {:dependencies {}, :dependents {:b #{}}}
```

The only way to clean the graph is to call remove-all on both nodes end egdes which seems counter intuitive

```clojure
(-> (dep/graph)
    (dep/depend :a :b)
    (dep/remove-all :a)
    (dep/remove-all :b))

;-> {:dependencies {}, :dependents {}}
```

**Comment by lgrapenthin** [comment]
Removing edges also seems to implicitly add nil under them

```clojure
(-> (dep/graph)
    (dep/remove-edge :a :b))

;-> {:dependencies {:a nil}, :dependents {:b nil}}
```

**Comment by stuartsierra** [comment]
Thank you for the report.

This Git repository is a copy of `clojure.tools.namespace.dependency` from [tools.namespace](https://github.com/clojure/tools.namespace) and is covered by the clojure-contrib process. Please file an issue at http://dev.clojure.org/jira/browse/TNS
