### ISSUE TITLE
Show full path for circular dependency exceptions

### ISSUE THREAD

**Issue by vemv** [stuartsierra/dependency#5]
Hi there!

Using `clojure.tools.namespace.dependency` (`clojure.tools` version). I assume both are the same. Reporting here seems more specific and agile.

I use this lib to detect circular dependencies among arbitrary objects. It works fine, but the error could be more informative for a certain case:

```
{:type clojure.lang.ExceptionInfo
   :message "Circular dependency between x and y"
   :data {:reason :clojure.tools.namespace.dependency/circular-dependency, :node x, :dependency y}
   :at [clojure.core$ex_info invokeStatic "core.clj" 4617]}
```

`x` and `y` are redacted data.

The problem is that neither x or y depend on each other directly, but via an indirect path.

It would be tremendously useful if the exception itself informed of the full faulty path, instead of just the beginning and end.

Example of desired exception:

 ```
 :data {:reason :clojure.tools.namespace.dependency/circular-dependency, :node x, :dependency y, :path [x a b c y]}
 ```

Hope it's possible.

Cheers - Victor

**Comment by stuartsierra** [comment]
Hi Victor,
Thanks for your interest in dependency! This repository is a mirror of the clojure.tools.namespace version, and all development will happen there under the terms of the [Clojure Contributor Agreement](https://clojure.org/community/contributing).

Please submit tickets and/or patches on the Clojure JIRA at https://dev.clojure.org/jira/browse/TNS

Thanks!
